# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: HRMS.API CI/CD Deployement

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: github
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - name: Configure Azure ACR
        uses: azure/docker-login@v4
        with:
          login-server: ${{vars.ACR_SERVER}}
          username: ${{secrets.ACR_USERNAME}}
          password: ${{secrets.ACR_PASSWORD}}
      
      - name: SHA Of the commit
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{github.sha}})
          echo "::set-output name=short_sha::$calculatedSha"
      
      - name: Build and Push Docker Image to ACR
        env:
          ACR_REGISTRY: ${{vars.ACR_SERVER}}
          IMAGE_TAG: ${{steps.vars.outputs.short_sha }}
        run: |
          docker buildx build -f HRMS.API/Dockerfile -t $ACR_REGISTRY/hrmsapi:$IMAGE_TAG -t $ACR_REGISTRY/hrmsapi:latest .
          docker push $ACR_REGISTRY/hrmsapi --all-tags
